//! Autostart on login via a systemd user unit
//! (`~/.config/systemd/user/inari.service`). The unit is anchored to
//! `graphical-session.target` so it starts with the desktop session (which
//! also provides the WAYLAND_DISPLAY/DISPLAY environment) and after
//! PipeWire is up.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::error::SinkError;

const UNIT_NAME: &str = "inari.service";

fn unit_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir.join("systemd").join("user").join(UNIT_NAME))
}

fn render_unit() -> Result<String, SinkError> {
    let exe = std::env::current_exe()
        .map_err(|e| SinkError::Config(format!("cannot resolve own executable path: {e}")))?;
    // Quote for systemd's unit syntax so paths with spaces (or quotes -
    // however unlikely) don't split into command + arguments.
    let exe = format!(
        "\"{}\"",
        exe.display().to_string().replace('\\', "\\\\").replace('"', "\\\"")
    );
    // Boot to tray on login when the user asked for it. Only the autostart
    // launch carries this flag, so manual launches still show the window.
    let exe = if crate::persistence::prefs::Prefs::load().start_minimized {
        format!("{exe} --minimized")
    } else {
        exe
    };
    Ok(format!(
        "# Generated by Inari. Re-enabling autostart rewrites this file,\n\
         # so the path tracks wherever the binary currently lives.\n\
         [Unit]\n\
         Description=Inari audio mixer\n\
         After=graphical-session.target pipewire.service wireplumber.service\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n",
        exe
    ))
}

fn systemctl(args: &[&str]) -> Result<std::process::Output, SinkError> {
    Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .map_err(|e| SinkError::Config(format!("systemctl --user {}: {e}", args.join(" "))))
}

pub fn is_enabled() -> bool {
    systemctl(&["is-enabled", UNIT_NAME])
        .map(|out| out.status.success())
        .unwrap_or(false)
}

/// Does this cgroup path put us inside `unit`?
///
/// Split out from [`running_as_unit`] so the interesting part - telling our own
/// unit apart from the transient `app-*.service` a desktop launcher wraps
/// manual starts in - is testable without a systemd session.
fn cgroup_names_unit(cgroup: &str, unit: &str) -> bool {
    cgroup.lines().any(|line| {
        // Format is `hierarchy:controllers:path`; only the path matters, and on
        // cgroup v2 the first two fields are empty.
        line.rsplit(':')
            .next()
            .map(|path| path.trim_end_matches('/').ends_with(&format!("/{unit}")))
            .unwrap_or(false)
    })
}

/// Are we running *as* the autostart unit?
///
/// `INVOCATION_ID` is the obvious test and the wrong one: systemd sets it for
/// every unit, and KDE wraps a manual launch in a transient
/// `app-<name>@<hash>.service` of its own. Restarting `inari.service` from
/// inside one of those would start a unit the user never asked to run - and
/// leave the launched instance behind. The cgroup path names the unit we are
/// actually in, so ask that instead.
pub fn running_as_unit() -> bool {
    fs::read_to_string("/proc/self/cgroup")
        .map(|c| cgroup_names_unit(&c, UNIT_NAME))
        .unwrap_or(false)
}

/// Ask systemd to restart our own unit; `true` if the job was queued.
///
/// `--no-block` is not optional here. The restart job's first half is stopping
/// this very process, so waiting for it to finish would wait on our own death.
/// Queue it and let systemd - which outlives us by definition - carry it out.
pub fn request_restart() -> bool {
    systemctl(&["--no-block", "restart", UNIT_NAME])
        .map(|out| out.status.success())
        .unwrap_or(false)
}

pub fn enable() -> Result<(), SinkError> {
    let path = unit_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    crate::persistence::write_atomic(&path, render_unit()?)?;

    for step in [&["daemon-reload"][..], &["enable", UNIT_NAME][..]] {
        let out = systemctl(step)?;
        if !out.status.success() {
            return Err(SinkError::Config(format!(
                "systemctl --user {} failed: {}",
                step.join(" "),
                String::from_utf8_lossy(&out.stderr).trim()
            )));
        }
    }
    Ok(())
}

pub fn disable() -> Result<(), SinkError> {
    let out = systemctl(&["disable", UNIT_NAME])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        // Disabling a unit that was never enabled is fine.
        if !stderr.contains("does not exist") {
            return Err(SinkError::Config(format!(
                "systemctl --user disable failed: {}",
                stderr.trim()
            )));
        }
    }
    let path = unit_path()?;
    if path.exists() {
        fs::remove_file(&path)?;
        let _ = systemctl(&["daemon-reload"]);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_renders_with_exe_and_session_anchor() {
        let unit = render_unit().expect("renders");
        assert!(unit.contains("[Unit]"));
        // Path is quoted so spaces don't split into command + args.
        assert!(unit.contains("ExecStart=\"/"));
        assert!(unit.contains("WantedBy=graphical-session.target"));
        assert!(unit.contains("After=graphical-session.target pipewire.service"));
    }

    /// The cgroup of an instance actually started by the autostart unit.
    const UNDER_UNIT: &str =
        "0::/user.slice/user-1000.slice/user@1000.service/app.slice/inari.service";

    /// What KDE's launcher produces for a manual start - captured from a real
    /// session. It is a systemd unit too, which is exactly why `INVOCATION_ID`
    /// cannot be used to tell the two apart.
    const UNDER_KDE_LAUNCHER: &str = "0::/user.slice/user-1000.slice/user@1000.service/\
         app.slice/app-net.local.smart\\x2dlauncher@7fd00cd58eaa49578ad6a3cc871e6d24.service";

    #[test]
    fn cgroup_detection_finds_our_own_unit() {
        assert!(cgroup_names_unit(UNDER_UNIT, UNIT_NAME));
        assert!(cgroup_names_unit(&format!("{UNDER_UNIT}/"), UNIT_NAME));
    }

    #[test]
    fn cgroup_detection_rejects_a_launcher_scope() {
        assert!(!cgroup_names_unit(UNDER_KDE_LAUNCHER, UNIT_NAME));
    }

    #[test]
    fn cgroup_detection_rejects_a_merely_similar_name() {
        // Suffix matching without the separator would accept these.
        assert!(!cgroup_names_unit("0::/app.slice/not-inari.service", UNIT_NAME));
        assert!(!cgroup_names_unit("0::/app.slice/inari.service.d", UNIT_NAME));
        assert!(!cgroup_names_unit("", UNIT_NAME));
    }

    #[test]
    fn cgroup_detection_reads_v1_style_lines() {
        // A hybrid hierarchy lists one line per controller; the unit is named
        // in the path field, not the first.
        let v1 = "12:pids:/user.slice/user-1000.slice/user@1000.service/inari.service\n\
                  0::/user.slice/user-1000.slice/user@1000.service/inari.service";
        assert!(cgroup_names_unit(v1, UNIT_NAME));
    }
}
