//! Autostart on login via a systemd user unit
//! (`~/.config/systemd/user/inari.service`). The unit is anchored to
//! `graphical-session.target` so it starts with the desktop session (which
//! also provides the WAYLAND_DISPLAY/DISPLAY environment) and after
//! PipeWire is up.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::error::SinkError;

const UNIT_NAME: &str = "inari.service";

fn unit_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir.join("systemd").join("user").join(UNIT_NAME))
}

fn render_unit() -> Result<String, SinkError> {
    let exe = std::env::current_exe()
        .map_err(|e| SinkError::Config(format!("cannot resolve own executable path: {e}")))?;
    // Quote for systemd's unit syntax so paths with spaces (or quotes -
    // however unlikely) don't split into command + arguments.
    let exe = format!(
        "\"{}\"",
        exe.display().to_string().replace('\\', "\\\\").replace('"', "\\\"")
    );
    // Boot to tray on login when the user asked for it. Only the autostart
    // launch carries this flag, so manual launches still show the window.
    let exe = if crate::persistence::prefs::Prefs::load().start_minimized {
        format!("{exe} --minimized")
    } else {
        exe
    };
    Ok(format!(
        "# Generated by Inari. Re-enabling autostart rewrites this file,\n\
         # so the path tracks wherever the binary currently lives.\n\
         [Unit]\n\
         Description=Inari audio mixer\n\
         After=graphical-session.target pipewire.service wireplumber.service\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n",
        exe
    ))
}

fn systemctl(args: &[&str]) -> Result<std::process::Output, SinkError> {
    Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .map_err(|e| SinkError::Config(format!("systemctl --user {}: {e}", args.join(" "))))
}

pub fn is_enabled() -> bool {
    systemctl(&["is-enabled", UNIT_NAME])
        .map(|out| out.status.success())
        .unwrap_or(false)
}

pub fn enable() -> Result<(), SinkError> {
    let path = unit_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    crate::persistence::write_atomic(&path, render_unit()?)?;

    for step in [&["daemon-reload"][..], &["enable", UNIT_NAME][..]] {
        let out = systemctl(step)?;
        if !out.status.success() {
            return Err(SinkError::Config(format!(
                "systemctl --user {} failed: {}",
                step.join(" "),
                String::from_utf8_lossy(&out.stderr).trim()
            )));
        }
    }
    Ok(())
}

pub fn disable() -> Result<(), SinkError> {
    let out = systemctl(&["disable", UNIT_NAME])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        // Disabling a unit that was never enabled is fine.
        if !stderr.contains("does not exist") {
            return Err(SinkError::Config(format!(
                "systemctl --user disable failed: {}",
                stderr.trim()
            )));
        }
    }
    let path = unit_path()?;
    if path.exists() {
        fs::remove_file(&path)?;
        let _ = systemctl(&["daemon-reload"]);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_renders_with_exe_and_session_anchor() {
        let unit = render_unit().expect("renders");
        assert!(unit.contains("[Unit]"));
        // Path is quoted so spaces don't split into command + args.
        assert!(unit.contains("ExecStart=\"/"));
        assert!(unit.contains("WantedBy=graphical-session.target"));
        assert!(unit.contains("After=graphical-session.target pipewire.service"));
    }
}
